### PR TITLE
add ProposerIndex() to BlindedBlocks

### PR DESCRIPTION
**Pull request by GalRogozinski**
### Description

Added missing method

### CODE REVIEW

**Comment by GalRogozinski** [comment]
@mcdee will you review?
Thanks in adavnce :-)

**Comment by GalRogozinski** [comment]
solved conflicts

btw @mcdee, I noticed you added a `RandaoReveal()` to api/versionedblindedbeaconblock.go but not to spec/versionedbeaconblock.go. Is this on purpose?

**Comment by mcdee** [comment]
Apologies for the delay on this.  I've been considering it, and my concern is that the interface is a subset of a beacon block rather than actually a beacon block.  So, for example, there is no `ExecutionPayload()` method which is something that a user seeing a `BeaconBlock` would reasonably expect to be able to obtain.

In general it's better to have interfaces with fewer functions, ideally 1.  Would it make sense to have interfaces as:

```
type BeaconBlockSlotProvider interface {
  Slot() (phase0.Slot, error)
}

type BeaconBlockProposerIndexProvider interface {
  ProposerIndex() (phase0.ValidatorIndex,error)
}

...
```

as that would allow a full range of interfaces that could cover both blinded and unblinded beacon blocks.

**Comment by GalRogozinski** [comment]
I changed the description and title of the PR accordingly

**Pull request merged**
